version: '3.1'

services:
  pynoplia:
    build: .
    command: python3 -m wsgi --port=8595
    restart: always
    environment:
      - VIRTUAL_HOST=pynora.ydns.eu
      - VIRTUAL_PORT=8595
    ports:
      - "8595:8595"
